// Privacy Policy — a structured placeholder (see ./legal.js).
//
// What it describes matches what the application actually holds: accounts and
// profiles, portfolios and deliverables, orders, payments and payouts, support
// tickets, notifications, and the audit trail behind administrative actions
// (00 §8). The session-storage note under "Cookies and local storage" describes
// the current build honestly.

export const PRIVACY_INTRO =
  'This notice explains what information BetterBlue collects when you use the marketplace, why we hold it, who it is shared with, and how long it is kept.'

/** Ordered sections; the page numbers them and builds its contents from them. */
export const PRIVACY_SECTIONS = Object.freeze([
  Object.freeze({
    id: 'about-this-notice',
    title: 'About this notice',
    paragraphs: Object.freeze([
      'BetterBlue operates a marketplace where businesses commission commercial content from creators. Running that marketplace means holding information about the people on both sides of an engagement, and about the engagements themselves.',
      'This notice covers the BetterBlue website and application. It should be read alongside the Terms of Service and the Content Policy.',
    ]),
  }),
  Object.freeze({
    id: 'information-we-collect',
    title: 'Information we collect',
    paragraphs: Object.freeze([
      'We collect information you give us, information generated by using the marketplace, and a small amount of technical information from your device.',
    ]),
    list: Object.freeze([
      'Account information — your name, email address, role, and password credentials.',
      'Profile information — for businesses, the company name, industry, and location; for creators, the tagline, biography, categories, rates, availability, and languages.',
      'Content you publish — portfolio work, content requests, proposals, deliverables, and the descriptions and metadata attached to them.',
      'Engagement records — orders, deliveries, revision requests, reviews, disputes and the evidence submitted with them, and the messages exchanged on an order.',
      'Payment records — the amount, currency, status, and timing of payments, commissions, and payouts. Card details are handled by the payment provider and are not stored by BetterBlue.',
      'Support and moderation records — the tickets you send us, the reports you make, and the decisions taken on content you submitted.',
      'Technical information — the device and browser you use, and basic usage information needed to keep the service working and secure.',
    ]),
  }),
  Object.freeze({
    id: 'how-we-use-information',
    title: 'How we use information',
    paragraphs: Object.freeze([
      'We use the information above to operate the marketplace and to meet obligations that come with it.',
    ]),
    list: Object.freeze([
      'To create and maintain your account and to authenticate you.',
      'To publish content requests, proposals, and portfolios to the members they are meant for.',
      'To process payments, hold them in escrow, release them, take commission, and pay out earnings.',
      'To review content against the Content Policy and to act on reports.',
      'To resolve disputes on the record of what was agreed and what was delivered.',
      'To send service notifications about your requests, proposals, orders, payments, and account.',
      'To keep the marketplace secure, prevent misuse, and meet our legal and record-keeping obligations.',
    ]),
  }),
  Object.freeze({
    id: 'public-information',
    title: 'Information other members can see',
    paragraphs: Object.freeze([
      'Some information is public by design. Creator profiles and approved portfolio work are visible to anyone browsing the marketplace, along with ratings and review text. Published content requests show the brief and the business that posted it.',
      'Private information — your email address, payment records, support tickets, and the contents of an order — is visible only to the parties to that engagement and to authorised BetterBlue staff.',
    ]),
  }),
  Object.freeze({
    id: 'sharing',
    title: 'Sharing information',
    paragraphs: Object.freeze([
      'We do not sell personal information. We share it only where it is needed to run the marketplace.',
    ]),
    list: Object.freeze([
      'With the other party to an engagement — a buyer and creator working on an order can see what the order requires them to.',
      'With service providers acting on our instructions, such as payment processing, file storage, and email delivery.',
      'With our Trust & Safety and support teams, where a review, a report, or a dispute requires it.',
      'Where the law requires it, or to protect the rights and safety of members of the marketplace.',
    ]),
  }),
  Object.freeze({
    id: 'retention',
    title: 'How long we keep it',
    paragraphs: Object.freeze([
      'Account and profile information is kept while your account exists. Records of orders, payments, commissions, payouts, moderation decisions, and disputes are kept after an engagement ends, because they evidence what was agreed and what was paid.',
      'Deactivating an account removes it from the marketplace but does not erase these records; accounts are closed by status change rather than deletion so obligations to other members can still be met.',
    ]),
  }),
  Object.freeze({
    id: 'your-rights',
    title: 'Your choices and rights',
    paragraphs: Object.freeze([
      'You can review and update your account and profile information at any time from your dashboard settings, and choose which notifications you receive.',
      'Depending on where you live, you may have the right to request a copy of the personal information we hold about you, ask us to correct it, ask us to delete it, or object to particular uses. Contact us and we will respond within the period the applicable law allows.',
    ]),
  }),
  Object.freeze({
    id: 'security',
    title: 'Security',
    paragraphs: Object.freeze([
      'We use technical and organisational measures to protect the information we hold, and limit staff access to what a role actually requires. Administrative actions on member accounts and content are recorded in an audit trail.',
      'No online service can promise perfect security. Use a strong, unique password and tell us immediately if you think your account has been compromised.',
    ]),
  }),
  Object.freeze({
    id: 'cookies',
    title: 'Cookies and local storage',
    paragraphs: Object.freeze([
      'BetterBlue stores your signed-in session in your browser so you stay signed in between visits, and remembers a small number of interface preferences. Clearing your browser storage signs you out and resets those preferences.',
      'We do not use advertising cookies or third-party tracking on the marketplace.',
    ]),
  }),
  Object.freeze({
    id: 'children',
    title: 'Children',
    paragraphs: Object.freeze([
      'BetterBlue is a marketplace for businesses and professional creators and is not intended for anyone under 18. We do not knowingly collect information from children. If you believe a child has created an account, contact us and we will remove it.',
    ]),
  }),
  Object.freeze({
    id: 'changes',
    title: 'Changes to this notice',
    paragraphs: Object.freeze([
      'We update this notice when the way we handle information changes. The date at the top of this page shows when the current version was published, and material changes are announced before they take effect.',
    ]),
  }),
  Object.freeze({
    id: 'contact',
    title: 'Contact',
    paragraphs: Object.freeze([
      'Questions about this notice, or a request about the information we hold about you, can be sent to our support team through the contact form.',
    ]),
  }),
])

/** Contents entries for `InfoPageLayout`, numbered to match the sections. */
export const PRIVACY_TOC = Object.freeze(
  PRIVACY_SECTIONS.map((section, index) => ({
    id: section.id,
    label: `${index + 1}. ${section.title}`,
  }))
)
