// Seed: `notifications` — the in-app bell feed (Prompt 05 §4.3).
//
// Every row is generated from an event that actually exists in the seeded
// data: a proposal that was really submitted, an order that was really
// funded, a dispute that was really opened. `entityType` + `entityId` are the
// deep link, and the integrity validator resolves both.
//
// The four demo accounts get the fullest feeds — mixed read and unread — so a
// first login has something meaningful in the bell menu. Unread counts are not
// stored on `users`: the app derives them at runtime with
// `GET /notifications?userId=…&read=false` (see docs/data-model.md).

import { NOTIFICATION_TYPE } from '../../src/constants/notificationTypes.js'
import { ENTITY_TYPE, compact, daysAgo, seqId } from '../seed-utils.js'
import { ADMIN_ID, buyerId, creatorId } from './users.js'
import { requestId } from './requests.js'
import { portfolioItems } from './portfolio.js'
import { orderFor } from './orders.js'
import { disputes } from './disputes.js'
import { payouts } from './finance.js'
import { affiliateEarnings } from './affiliate.js'

const order = (key) => orderFor(key).id
const itemNamed = (title) => portfolioItems.find((item) => item.title === title).id
const disputeOn = (key) =>
  disputes.find((dispute) => dispute.orderId === orderFor(key).id).id

/**
 * A payout by whose it is and what it is for, rather than by its index.
 *
 * Prompt 27 fix: two rows here linked to `payouts[0]` and `payouts[2]` by
 * position, and the positions had moved — Ava's "$1,200 sent" pointed at her
 * $500 *rejected* request, and Liam's "$1,500 processing" pointed at Ava's
 * payout entirely. Both were invisible until the notification centre made the
 * rows clickable. Looking them up by creator and amount cannot drift.
 */
const payoutOf = (creator, amount) => {
  const match = payouts.find(
    (payout) => payout.creatorId === creatorId(creator) && payout.amount === amount
  )
  if (!match) throw new Error(`No ${creator} payout of ${amount}`)
  return match.id
}

const NOTIFICATION_SOURCE = [
  /* --- Buyer demo account: Nora at Verde Kitchen ------------------------- */
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.PROPOSAL_RECEIVED,
    title: 'New proposal from Ava Martinez',
    body: 'Ava Martinez proposed $820 for “20 seasonal menu photos for our autumn dinner service”, delivered in 9 days.',
    entityType: ENTITY_TYPE.REQUEST,
    entityId: requestId('open_verde_menu'),
    read: true,
    daysAgo: 7.5,
  },
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.PROPOSAL_RECEIVED,
    title: 'New proposal from Noah Feldman',
    body: 'Your autumn menu brief has three proposals waiting. The newest quotes $640 with a 7-day turnaround.',
    entityType: ENTITY_TYPE.REQUEST,
    entityId: requestId('open_verde_menu'),
    read: false,
    daysAgo: 5.5,
  },
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.DELIVERY_SUBMITTED,
    title: 'Ava Martinez submitted a delivery',
    body: 'Three vertical reels are ready to review on “Three vertical reels for the autumn menu launch”.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_verde_reel'),
    read: true,
    daysAgo: 13,
  },
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.ORDER_COMPLETED,
    title: 'Order completed',
    body: '“Training films for the new kitchen onboarding programme” is complete. Leave a review to help other buyers.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('h22'),
    read: true,
    daysAgo: 23.5,
  },
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.SYSTEM_ANNOUNCEMENT,
    title: 'Escrow protection now covers revisions',
    body: 'Payments stay held until you accept a delivery, including while a revision is in progress. Nothing to do — this applies to your open orders already.',
    read: false,
    daysAgo: 9,
  },

  /* --- Creator demo account: Ava Martinez -------------------------------- */
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.PROPOSAL_SHORTLISTED,
    title: 'Your proposal was shortlisted',
    body: 'Verde Kitchen shortlisted your proposal on “20 seasonal menu photos for our autumn dinner service”.',
    entityType: ENTITY_TYPE.REQUEST,
    entityId: requestId('open_verde_menu'),
    read: false,
    daysAgo: 7,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.PROPOSAL_ACCEPTED,
    title: 'Cocoa & Co accepted your proposal',
    body: 'Your $940 proposal for “15 lifestyle photos for a single-origin gift box launch” was accepted.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_cocoa_gift'),
    read: true,
    daysAgo: 6,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.ORDER_PAID,
    title: 'Order funded — you can start',
    body: 'Cocoa & Co funded the order. $940 is held in escrow and released to you when the delivery is accepted.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_cocoa_gift'),
    read: true,
    daysAgo: 5.8,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.REVISION_REQUESTED,
    title: 'Verde Kitchen requested a revision',
    body: 'Two changes on “Three vertical reels for the autumn menu launch”: a length trim and a caption correction.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_verde_reel'),
    read: false,
    daysAgo: 11,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.PAYMENT_RELEASED,
    title: 'Payment released',
    body: '$552 has been added to your balance from “Gift box photography for the winter hamper range”, after the 20% platform commission.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('h15'),
    read: true,
    daysAgo: 46,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.PAYOUT_PROCESSED,
    title: 'Payout sent to your bank',
    body: 'Your $1,200 payout has been processed and should arrive within three working days.',
    entityType: ENTITY_TYPE.PAYOUT,
    entityId: payoutOf('ava', 1200),
    read: true,
    daysAgo: 21,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.AFFILIATE_CONVERSION,
    title: 'A referral converted',
    body: 'Craftware Tools completed their first order through your referral code. Commission has been added to your affiliate balance.',
    entityType: ENTITY_TYPE.AFFILIATE_EARNING,
    entityId: affiliateEarnings[0].id,
    read: true,
    daysAgo: 76,
  },

  /* --- Admin demo account: Maya Chen ------------------------------------- */
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.DISPUTE_OPENED,
    title: 'New dispute: late delivery',
    body: 'Pulse SaaS opened a dispute on the reporting dashboard explainer series. Nothing has been submitted and the order is 18 days past its delivery date.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_pulse_explainer'),
    read: false,
    daysAgo: 6,
  },
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.DISPUTE_MESSAGE,
    title: 'New message on a dispute you own',
    body: 'The creator replied on the Craftware Tools scope dispute. Awaiting the buyer’s confirmation of the part delivery date.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_craftware_demo'),
    read: false,
    daysAgo: 9,
  },
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.DISPUTE_RESOLVED,
    title: 'Dispute resolved',
    body: 'The Atlas Travel villa dispute was resolved with a partial refund of $205. Both parties accepted the outcome.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('completed_atlas_villa'),
    read: true,
    daysAgo: 18,
  },
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.SYSTEM_ANNOUNCEMENT,
    title: 'Moderation SLA is now two days',
    body: 'The review SLA in platform settings moved to two days. Queue items older than that are highlighted in the moderation console.',
    entityType: ENTITY_TYPE.PLATFORM_SETTINGS,
    entityId: 'platformSettings',
    read: true,
    daysAgo: 12,
  },

  /* --- Super admin demo account: Elena Marsh ------------------------------ */
  {
    userId: ADMIN_ID.SUPER,
    type: NOTIFICATION_TYPE.ACCOUNT_STATUS_CHANGED,
    title: 'Creator account suspended',
    body: 'Chloe Dubois was suspended pending a licensing review, following an upheld report and an unresolved non-delivery dispute.',
    entityType: ENTITY_TYPE.USER,
    entityId: creatorId('chloe'),
    read: true,
    daysAgo: 29,
  },
  {
    userId: ADMIN_ID.SUPER,
    type: NOTIFICATION_TYPE.DISPUTE_OPENED,
    title: 'Dispute volume this week',
    body: 'Two disputes are open and one is unassigned. The oldest has been waiting six days for triage.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_pulse_explainer'),
    read: false,
    daysAgo: 4,
  },
  {
    userId: ADMIN_ID.SUPER,
    type: NOTIFICATION_TYPE.SYSTEM_ANNOUNCEMENT,
    title: 'Platform settings updated',
    body: 'Commission, payout minimum, and moderation SLA were reviewed. The affiliate programme stays enabled at 10%.',
    entityType: ENTITY_TYPE.PLATFORM_SETTINGS,
    entityId: 'platformSettings',
    read: true,
    daysAgo: 12,
  },

  /* --- Other buyers ------------------------------------------------------- */
  {
    userId: buyerId('bloom'),
    type: NOTIFICATION_TYPE.DELIVERY_SUBMITTED,
    title: 'Zoe Okonkwo submitted a delivery',
    body: 'Swatch and texture photography for the tinted SPF range is ready to review. Auto-acceptance runs in one day.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_bloom_texture'),
    read: false,
    daysAgo: 4,
  },
  {
    userId: buyerId('bloom'),
    type: NOTIFICATION_TYPE.DISPUTE_RESOLVED,
    title: 'Your dispute was resolved',
    body: 'The full amount of $610 has been refunded to your payment method after no deliverables were submitted.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('cancelled_bloom_serum'),
    read: true,
    daysAgo: 33,
  },
  {
    userId: buyerId('atlas'),
    type: NOTIFICATION_TYPE.DELIVERY_SUBMITTED,
    title: 'Isla Bergstrom submitted a delivery',
    body: 'Property photography for the three Algarve partner hotels is ready to review.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_atlas_hotel'),
    read: false,
    daysAgo: 2,
  },
  {
    userId: buyerId('pulse'),
    type: NOTIFICATION_TYPE.PROPOSAL_RECEIVED,
    title: 'Four proposals on your walkthrough brief',
    body: 'Quotes range from $820 to $1,200 with turnarounds between 10 and 16 days.',
    entityType: ENTITY_TYPE.REQUEST,
    entityId: requestId('open_pulse_walkthrough'),
    read: false,
    daysAgo: 0.8,
  },
  {
    userId: buyerId('nimbus'),
    type: NOTIFICATION_TYPE.PROPOSAL_ACCEPTED,
    title: 'Your order is waiting for payment',
    body: 'You accepted Liam Chen’s proposal for the connected training app film. Fund the order to start the clock.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_nimbus_app'),
    read: false,
    daysAgo: 1,
  },
  {
    userId: buyerId('craftware'),
    type: NOTIFICATION_TYPE.DISPUTE_MESSAGE,
    title: 'BetterBlue replied to your dispute',
    body: 'A reviewer has asked when the plunge head is expected, so the fourth film can be completed rather than refunded.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_craftware_demo'),
    read: true,
    daysAgo: 16,
  },
  {
    userId: buyerId('urbannest'),
    type: NOTIFICATION_TYPE.DISPUTE_RESOLVED,
    title: 'Dispute closed',
    body: 'The delivered masters were confirmed sharp at full resolution, so the payment has been released to the creator.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('completed_urbannest_loft'),
    read: true,
    daysAgo: 14,
  },
  {
    userId: buyerId('cocoa'),
    type: NOTIFICATION_TYPE.ORDER_PAID,
    title: 'Payment held in escrow',
    body: '$940 is held for “15 lifestyle photos for a single-origin gift box launch” and releases when you accept the delivery.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_cocoa_gift'),
    read: true,
    daysAgo: 5.8,
  },

  /* --- Other creators ----------------------------------------------------- */
  {
    userId: creatorId('liam'),
    type: NOTIFICATION_TYPE.PROPOSAL_ACCEPTED,
    title: 'Nimbus Fitness accepted your proposal',
    body: 'The order opens once the buyer funds it. You will be notified the moment payment is held.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_nimbus_app'),
    read: true,
    daysAgo: 1,
  },
  {
    userId: creatorId('liam'),
    type: NOTIFICATION_TYPE.PAYOUT_PROCESSED,
    title: 'Payout is being processed',
    body: 'Your $1,500 payout has moved to processing and will be marked paid once the transfer settles.',
    entityType: ENTITY_TYPE.PAYOUT,
    entityId: payoutOf('liam', 1500),
    read: false,
    daysAgo: 4,
  },
  {
    userId: creatorId('zoe'),
    type: NOTIFICATION_TYPE.PAYMENT_RELEASED,
    title: 'Payment released',
    body: '$816 has been added to your balance from the barrier repair campaign film.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('completed_bloom_campaign'),
    read: true,
    daysAgo: 31,
  },
  {
    userId: creatorId('zoe'),
    type: NOTIFICATION_TYPE.MODERATION_APPROVED,
    title: 'Portfolio item approved',
    body: 'Your studio campaign film for the sustainable denim drop was approved and is now live on your public profile.',
    entityType: ENTITY_TYPE.PORTFOLIO_ITEM,
    entityId: itemNamed('Studio campaign film for a sustainable denim drop'),
    read: false,
    daysAgo: 8,
  },
  {
    userId: creatorId('diego'),
    type: NOTIFICATION_TYPE.MODERATION_REVISION,
    title: 'Changes requested on your submission',
    body: 'The resistance band demonstration set needs changes before it can be published. The reviewer’s notes are on the item.',
    entityType: ENTITY_TYPE.PORTFOLIO_ITEM,
    entityId: itemNamed('Resistance band range demonstration set'),
    read: false,
    daysAgo: 17,
  },
  {
    userId: creatorId('yuki'),
    type: NOTIFICATION_TYPE.REVISION_REQUESTED,
    title: 'UrbanNest Interiors requested a revision',
    body: 'Six frames in the white finish need a re-grade to match the neutral reference. Everything else is approved.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_urbannest_shelf'),
    read: false,
    daysAgo: 7,
  },
  {
    userId: creatorId('sara'),
    type: NOTIFICATION_TYPE.DISPUTE_OPENED,
    title: 'A dispute was opened on your order',
    body: 'Pulse SaaS opened a late delivery dispute. Respond in the case thread with your current status and expected delivery date.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_pulse_explainer'),
    read: true,
    daysAgo: 6,
  },
  {
    userId: creatorId('noah'),
    type: NOTIFICATION_TYPE.DISPUTE_OPENED,
    title: 'A dispute was opened on your order',
    body: 'Craftware Tools raised a scope dispute about the missing fourth film. A reviewer has been assigned.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_craftware_demo'),
    read: true,
    daysAgo: 18,
  },
  {
    userId: creatorId('isla'),
    type: NOTIFICATION_TYPE.PAYMENT_RELEASED,
    title: 'Payment released',
    body: '$784 has been added to your balance from the Porto guesthouse property set.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('h12'),
    read: true,
    daysAgo: 54,
  },
  {
    userId: creatorId('mateo'),
    type: NOTIFICATION_TYPE.MODERATION_REVISION,
    title: 'Changes requested on your submission',
    body: 'The lakeside venue tour film needs changes before it can be published. Update it and send it back for review.',
    entityType: ENTITY_TYPE.PORTFOLIO_ITEM,
    entityId: itemNamed('Lakeside venue tour film'),
    read: false,
    daysAgo: 12,
  },
  {
    userId: creatorId('mateo'),
    type: NOTIFICATION_TYPE.DISPUTE_RESOLVED,
    title: 'Dispute resolved with a partial refund',
    body: 'A quarter of the order value was returned to Atlas Travel Co and $492 was released to your balance.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('completed_atlas_villa'),
    read: true,
    daysAgo: 18,
  },
  {
    userId: creatorId('ethan'),
    type: NOTIFICATION_TYPE.MODERATION_REJECTED,
    title: 'Submission rejected',
    body: 'The new-build show home series is missing category, content type, and usage details. Add them and re-submit.',
    entityType: ENTITY_TYPE.PORTFOLIO_ITEM,
    entityId: itemNamed('New-build show home series'),
    read: false,
    daysAgo: 6,
  },
  {
    userId: creatorId('chloe'),
    type: NOTIFICATION_TYPE.ACCOUNT_STATUS_CHANGED,
    title: 'Your account has been suspended',
    body: 'Your account is suspended while our Trust & Safety team completes a licensing review. Payouts are on hold and your balance stays intact. Contact support if you have questions.',
    entityType: ENTITY_TYPE.USER,
    entityId: creatorId('chloe'),
    read: true,
    daysAgo: 29,
  },
  {
    userId: creatorId('amara'),
    type: NOTIFICATION_TYPE.ORDER_COMPLETED,
    title: 'Order completed',
    body: 'Cocoa & Co accepted the flagship cafe opening coverage and left a 4-star review.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('h24'),
    read: true,
    daysAgo: 18,
  },

  /* --- Prompt 27: filling out the four demo feeds ------------------------- */
  //
  // The notification centre (§9) asks for at least twelve varied rows on each
  // demo account, spread across categories and across days, so the day grouping,
  // the category chips, the unread filter, and "Load more" all have something to
  // work on the moment somebody signs in. Every row below still describes an
  // event that exists in the seeded data — nothing is invented to pad a filter.
  //
  // One honest gap: the demo **buyer** has no Payments row, because a buyer only
  // ever receives `payment_refunded` and Verde Kitchen has no refunded order.
  // Inventing one would have made the chip lead to a receipt that is not in the
  // ledger. The chip renders and correctly comes back empty.

  /* Buyer demo account: Nora at Verde Kitchen — to 13 rows */
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.PROPOSAL_DECLINED,
    title: 'A proposal was withdrawn',
    body: 'One of the creators on “20 seasonal menu photos for our autumn dinner service” has withdrawn their proposal. The others are unaffected.',
    entityType: ENTITY_TYPE.REQUEST,
    entityId: requestId('open_verde_menu'),
    read: false,
    daysAgo: 3,
  },
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.ORDER_PAID,
    title: 'Payment held in escrow',
    body: '$520 is held for “Pastry counter stills for the morning service page” and releases to Ava Martinez when you accept the delivery.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_verde_pastry'),
    read: true,
    daysAgo: 6,
  },
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.DELIVERY_SUBMITTED,
    title: 'Ava Martinez submitted a delivery',
    body: 'Twelve finished images for the pastry counter page are ready to review, including both baker frames with releases on file.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_verde_pastry'),
    read: false,
    daysAgo: 1,
  },
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.ORDER_COMPLETED,
    title: 'Order completed',
    body: '“Supper club coverage for the harvest series” has been completed and the payment released to Amara Osei from escrow.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('h29'),
    read: true,
    daysAgo: 8,
  },
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.DISPUTE_OPENED,
    title: 'Your dispute has been received',
    body: 'A reviewer has been assigned to the winter chef’s table tasting menu case. You will hear from them in the case thread.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_verde_tasting'),
    read: true,
    daysAgo: 12,
  },
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.DISPUTE_MESSAGE,
    title: 'BetterBlue replied to your dispute',
    body: 'A reviewer has asked whether the two missing courses are back on the Friday menu, and whether a return visit works for you.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_verde_tasting'),
    read: false,
    daysAgo: 4,
  },
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.DISPUTE_MESSAGE,
    title: 'New message on the courtyard films dispute',
    body: 'A reviewer has watched both cuts against the brief and asked the creator whether a reshoot at dusk is possible.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_verde_courtyard'),
    read: true,
    daysAgo: 5,
  },
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.SYSTEM_ANNOUNCEMENT,
    title: 'Content Policy updated',
    body: 'The Content Policy has been restated with clearer examples of what may and may not be commissioned. Nothing you have briefed is affected.',
    read: true,
    daysAgo: 31,
  },

  /* Creator demo account: Ava Martinez — to 15 rows */
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.DELIVERY_ACCEPTED,
    title: 'Delivery accepted',
    body: 'Verde Kitchen accepted the ingredient sourcing stills. The escrow has been released to you.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('h27'),
    read: true,
    daysAgo: 16,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.ORDER_COMPLETED,
    title: 'Order completed',
    body: '“Barista process films for the seasonal drinks menu” is complete and $576 has been added to your balance, after commission.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('h26'),
    read: true,
    daysAgo: 19,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.PAYOUT_REQUESTED,
    title: 'Payout requested',
    body: 'Your $600 payout request has been received and is being processed. It is reserved out of your available balance until it settles.',
    entityType: ENTITY_TYPE.PAYOUT,
    entityId: payoutOf('ava', 600),
    read: true,
    daysAgo: 5,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.DISPUTE_OPENED,
    title: 'A dispute was opened on your order',
    body: 'Verde Kitchen raised a quality dispute about the courtyard films. Respond in the case thread — a reviewer has been assigned.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_verde_courtyard'),
    read: true,
    daysAgo: 8,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.DISPUTE_MESSAGE,
    title: 'A reviewer is waiting on you',
    body: 'BetterBlue has asked whether a reshoot at dusk with the heaters lit is possible, and by when. The case is waiting on your reply.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_verde_courtyard'),
    read: false,
    daysAgo: 3,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.MODERATION_APPROVED,
    title: 'Portfolio item approved',
    body: 'Your bakery counter lifestyle set was approved and is now live on your public profile.',
    entityType: ENTITY_TYPE.PORTFOLIO_ITEM,
    entityId: itemNamed('Bakery counter lifestyle set for a cafe group'),
    read: true,
    daysAgo: 11,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.SYSTEM_ANNOUNCEMENT,
    title: 'Payout minimum lowered to $50',
    body: 'You can now withdraw from a smaller balance. The processing time is unchanged at three working days.',
    read: false,
    daysAgo: 15,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.PROPOSAL_DECLINED,
    title: 'A brief you proposed on was closed',
    body: 'Cocoa & Co closed “Seasonal gift box photography for a limited spring range” without awarding it, so your proposal has ended.',
    entityType: ENTITY_TYPE.REQUEST,
    entityId: requestId('closed_cocoa_easter'),
    read: true,
    daysAgo: 34,
  },

  /* Admin demo account: Maya Chen — to 12 rows */
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.DISPUTE_OPENED,
    title: 'New dispute: scope mismatch',
    body: 'Verde Kitchen opened a scope dispute on the winter chef’s table tasting menu — six of eight courses covered. Assigned to you.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_verde_tasting'),
    read: true,
    daysAgo: 12,
  },
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.DISPUTE_OPENED,
    title: 'New dispute: quality issue',
    body: 'Verde Kitchen opened a quality dispute on the courtyard dining films. Two of three delivered, heaters unlit in both.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_verde_courtyard'),
    read: true,
    daysAgo: 8,
  },
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.DISPUTE_MESSAGE,
    title: 'New message on an escalated case',
    body: 'The buyer has replied on the marina resort non-delivery case. Still nothing submitted, and the print slot cannot be held.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_atlas_marina'),
    read: false,
    daysAgo: 5,
  },
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.DISPUTE_RESOLVED,
    title: 'Dispute closed in the creator’s favour',
    body: 'The loft showroom case was closed after the master files were confirmed sharp at full resolution. Payment released.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('completed_urbannest_loft'),
    read: true,
    daysAgo: 14,
  },
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.MODERATION_REJECTED,
    title: 'Your review decision was recorded',
    body: 'The new-build show home series was rejected for missing category, content type, and usage details. The creator has been told what to add.',
    entityType: ENTITY_TYPE.PORTFOLIO_ITEM,
    entityId: itemNamed('New-build show home series'),
    read: true,
    daysAgo: 6,
  },
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.MODERATION_REVISION,
    title: 'Your review decision was recorded',
    body: 'The lakeside venue tour film was sent back for changes. It returns to the queue when the creator re-submits.',
    entityType: ENTITY_TYPE.PORTFOLIO_ITEM,
    entityId: itemNamed('Lakeside venue tour film'),
    read: true,
    daysAgo: 12,
  },
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.ACCOUNT_STATUS_CHANGED,
    title: 'Creator account suspended',
    body: 'Chloe Dubois was suspended pending a licensing review. Payouts are on hold and the balance is untouched.',
    entityType: ENTITY_TYPE.USER,
    entityId: creatorId('chloe'),
    read: true,
    daysAgo: 29,
  },
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.SYSTEM_ANNOUNCEMENT,
    title: 'Content Policy examples expanded',
    body: 'The policy now carries worked examples for each prohibited category, so review notes can cite one rather than paraphrase.',
    read: false,
    daysAgo: 31,
  },

  /* Super admin demo account: Elena Marsh — to 12 rows */
  {
    userId: ADMIN_ID.SUPER,
    type: NOTIFICATION_TYPE.DISPUTE_MESSAGE,
    title: 'Escalated case still open',
    body: 'The marina resort non-delivery case has had a reply but no files. Nineteen days open, five since the last decision point.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_atlas_marina'),
    read: false,
    daysAgo: 5,
  },
  {
    userId: ADMIN_ID.SUPER,
    type: NOTIFICATION_TYPE.DISPUTE_RESOLVED,
    title: 'Partial refund issued',
    body: 'The villa and terrace case closed with a quarter of the order value returned to Atlas Travel Co and the rest released.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('completed_atlas_villa'),
    read: true,
    daysAgo: 18,
  },
  {
    userId: ADMIN_ID.SUPER,
    type: NOTIFICATION_TYPE.MODERATION_APPROVED,
    title: 'Content approved',
    body: 'The studio campaign film for the sustainable denim drop cleared review and is live on the creator’s profile.',
    entityType: ENTITY_TYPE.PORTFOLIO_ITEM,
    entityId: itemNamed('Studio campaign film for a sustainable denim drop'),
    read: true,
    daysAgo: 8,
  },
  {
    userId: ADMIN_ID.SUPER,
    type: NOTIFICATION_TYPE.MODERATION_REJECTED,
    title: 'Submission rejected',
    body: 'The new-build show home series was rejected for incomplete metadata. Second rejection for this creator this month.',
    entityType: ENTITY_TYPE.PORTFOLIO_ITEM,
    entityId: itemNamed('New-build show home series'),
    read: false,
    daysAgo: 6,
  },
  {
    userId: ADMIN_ID.SUPER,
    type: NOTIFICATION_TYPE.PAYOUT_REQUESTED,
    title: 'Payout awaiting review',
    body: 'Isla Bergstrom has requested $900. It is the oldest unprocessed settlement in the queue.',
    entityType: ENTITY_TYPE.PAYOUT,
    entityId: payoutOf('isla', 900),
    read: false,
    daysAgo: 2,
  },
  {
    userId: ADMIN_ID.SUPER,
    type: NOTIFICATION_TYPE.PAYOUT_PROCESSED,
    title: 'Payout moved to processing',
    body: 'Liam Chen’s $1,500 payout was approved and is with the bank. It settles to paid once the transfer clears.',
    entityType: ENTITY_TYPE.PAYOUT,
    entityId: payoutOf('liam', 1500),
    read: true,
    daysAgo: 4,
  },
  {
    userId: ADMIN_ID.SUPER,
    type: NOTIFICATION_TYPE.PAYMENT_REFUNDED,
    title: 'Full refund issued',
    body: '$610 was returned to Bloom Botanics after no deliverables were submitted on the serum packaging order.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('cancelled_bloom_serum'),
    read: true,
    daysAgo: 33,
  },
  {
    userId: ADMIN_ID.SUPER,
    type: NOTIFICATION_TYPE.ORDER_CANCELLED,
    title: 'Order cancelled before payment',
    body: 'The winter travel showcase recap was cancelled before it was funded, so nothing was charged and nothing is owed.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('cancelled_atlas_winter'),
    read: true,
    daysAgo: 21,
  },
  {
    userId: ADMIN_ID.SUPER,
    type: NOTIFICATION_TYPE.SYSTEM_ANNOUNCEMENT,
    title: 'Weekly marketplace summary',
    body: 'Twelve orders funded, nine completed, two disputes opened, and one account suspended in the last seven days.',
    read: false,
    daysAgo: 2,
  },
]

export const notifications = NOTIFICATION_SOURCE.map((source, index) =>
  // `entityType`/`entityId` are optional — a platform announcement links to
  // nothing in particular, so both keys are omitted rather than nulled.
  compact({
    id: seqId('ntf', index + 1),
    userId: source.userId,
    type: source.type,
    title: source.title,
    body: source.body,
    entityType: source.entityType,
    entityId: source.entityId,
    read: source.read,
    createdAt: daysAgo(source.daysAgo, 20, 15),
  })
)
