// Seed: `notifications` — the in-app bell feed (Prompt 05 §4.3).
//
// Every row is generated from an event that actually exists in the seeded
// data: a proposal that was really submitted, an order that was really
// funded, a dispute that was really opened. `entityType` + `entityId` are the
// deep link, and the integrity validator resolves both.
//
// The four demo accounts get the fullest feeds — mixed read and unread — so a
// first login has something meaningful in the bell menu. Unread counts are not
// stored on `users`: the app derives them at runtime with
// `GET /notifications?userId=…&read=false` (see docs/data-model.md).

import { NOTIFICATION_TYPE } from '../../src/constants/notificationTypes.js'
import { ENTITY_TYPE, compact, daysAgo, seqId } from '../seed-utils.js'
import { ADMIN_ID, buyerId, creatorId } from './users.js'
import { requestId } from './requests.js'
import { portfolioItems } from './portfolio.js'
import { orderFor } from './orders.js'
import { disputes } from './disputes.js'
import { payouts } from './finance.js'
import { affiliateEarnings } from './affiliate.js'

const order = (key) => orderFor(key).id
const itemNamed = (title) => portfolioItems.find((item) => item.title === title).id
const disputeOn = (key) =>
  disputes.find((dispute) => dispute.orderId === orderFor(key).id).id

const NOTIFICATION_SOURCE = [
  /* --- Buyer demo account: Nora at Verde Kitchen ------------------------- */
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.PROPOSAL_RECEIVED,
    title: 'New proposal from Ava Martinez',
    body: 'Ava Martinez proposed $820 for “20 seasonal menu photos for our autumn dinner service”, delivered in 9 days.',
    entityType: ENTITY_TYPE.REQUEST,
    entityId: requestId('open_verde_menu'),
    read: true,
    daysAgo: 7.5,
  },
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.PROPOSAL_RECEIVED,
    title: 'New proposal from Noah Feldman',
    body: 'Your autumn menu brief has three proposals waiting. The newest quotes $640 with a 7-day turnaround.',
    entityType: ENTITY_TYPE.REQUEST,
    entityId: requestId('open_verde_menu'),
    read: false,
    daysAgo: 5.5,
  },
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.DELIVERY_SUBMITTED,
    title: 'Ava Martinez submitted a delivery',
    body: 'Three vertical reels are ready to review on “Three vertical reels for the autumn menu launch”.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_verde_reel'),
    read: true,
    daysAgo: 13,
  },
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.ORDER_COMPLETED,
    title: 'Order completed',
    body: '“Training films for the new kitchen onboarding programme” is complete. Leave a review to help other buyers.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('h22'),
    read: true,
    daysAgo: 23.5,
  },
  {
    userId: buyerId('verde'),
    type: NOTIFICATION_TYPE.SYSTEM_ANNOUNCEMENT,
    title: 'Escrow protection now covers revisions',
    body: 'Payments stay held until you accept a delivery, including while a revision is in progress. Nothing to do — this applies to your open orders already.',
    read: false,
    daysAgo: 9,
  },

  /* --- Creator demo account: Ava Martinez -------------------------------- */
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.PROPOSAL_SHORTLISTED,
    title: 'Your proposal was shortlisted',
    body: 'Verde Kitchen shortlisted your proposal on “20 seasonal menu photos for our autumn dinner service”.',
    entityType: ENTITY_TYPE.REQUEST,
    entityId: requestId('open_verde_menu'),
    read: false,
    daysAgo: 7,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.PROPOSAL_ACCEPTED,
    title: 'Cocoa & Co accepted your proposal',
    body: 'Your $940 proposal for “15 lifestyle photos for a single-origin gift box launch” was accepted.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_cocoa_gift'),
    read: true,
    daysAgo: 6,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.ORDER_PAID,
    title: 'Order funded — you can start',
    body: 'Cocoa & Co funded the order. $940 is held in escrow and released to you when the delivery is accepted.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_cocoa_gift'),
    read: true,
    daysAgo: 5.8,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.REVISION_REQUESTED,
    title: 'Verde Kitchen requested a revision',
    body: 'Two changes on “Three vertical reels for the autumn menu launch”: a length trim and a caption correction.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_verde_reel'),
    read: false,
    daysAgo: 11,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.PAYMENT_RELEASED,
    title: 'Payment released',
    body: '$552 has been added to your balance from “Gift box photography for the winter hamper range”, after the 20% platform commission.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('h15'),
    read: true,
    daysAgo: 46,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.PAYOUT_PROCESSED,
    title: 'Payout sent to your bank',
    body: 'Your $1,200 payout has been processed and should arrive within three working days.',
    entityType: ENTITY_TYPE.PAYOUT,
    entityId: payouts[0].id,
    read: true,
    daysAgo: 21,
  },
  {
    userId: creatorId('ava'),
    type: NOTIFICATION_TYPE.AFFILIATE_CONVERSION,
    title: 'A referral converted',
    body: 'Craftware Tools completed their first order through your referral code. Commission has been added to your affiliate balance.',
    entityType: ENTITY_TYPE.AFFILIATE_EARNING,
    entityId: affiliateEarnings[0].id,
    read: true,
    daysAgo: 76,
  },

  /* --- Admin demo account: Maya Chen ------------------------------------- */
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.DISPUTE_OPENED,
    title: 'New dispute: late delivery',
    body: 'Pulse SaaS opened a dispute on the reporting dashboard explainer series. Nothing has been submitted and the order is 18 days past its delivery date.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_pulse_explainer'),
    read: false,
    daysAgo: 6,
  },
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.DISPUTE_MESSAGE,
    title: 'New message on a dispute you own',
    body: 'The creator replied on the Craftware Tools scope dispute. Awaiting the buyer’s confirmation of the part delivery date.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_craftware_demo'),
    read: false,
    daysAgo: 9,
  },
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.DISPUTE_RESOLVED,
    title: 'Dispute resolved',
    body: 'The Atlas Travel villa dispute was resolved with a partial refund of $205. Both parties accepted the outcome.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('completed_atlas_villa'),
    read: true,
    daysAgo: 18,
  },
  {
    userId: ADMIN_ID.MAYA,
    type: NOTIFICATION_TYPE.SYSTEM_ANNOUNCEMENT,
    title: 'Moderation SLA is now two days',
    body: 'The review SLA in platform settings moved to two days. Queue items older than that are highlighted in the moderation console.',
    entityType: ENTITY_TYPE.PLATFORM_SETTINGS,
    entityId: 'platformSettings',
    read: true,
    daysAgo: 12,
  },

  /* --- Super admin demo account: Elena Marsh ------------------------------ */
  {
    userId: ADMIN_ID.SUPER,
    type: NOTIFICATION_TYPE.ACCOUNT_STATUS_CHANGED,
    title: 'Creator account suspended',
    body: 'Chloe Dubois was suspended pending a licensing review, following an upheld report and an unresolved non-delivery dispute.',
    entityType: ENTITY_TYPE.USER,
    entityId: creatorId('chloe'),
    read: true,
    daysAgo: 29,
  },
  {
    userId: ADMIN_ID.SUPER,
    type: NOTIFICATION_TYPE.DISPUTE_OPENED,
    title: 'Dispute volume this week',
    body: 'Two disputes are open and one is unassigned. The oldest has been waiting six days for triage.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_pulse_explainer'),
    read: false,
    daysAgo: 4,
  },
  {
    userId: ADMIN_ID.SUPER,
    type: NOTIFICATION_TYPE.SYSTEM_ANNOUNCEMENT,
    title: 'Platform settings updated',
    body: 'Commission, payout minimum, and moderation SLA were reviewed. The affiliate programme stays enabled at 10%.',
    entityType: ENTITY_TYPE.PLATFORM_SETTINGS,
    entityId: 'platformSettings',
    read: true,
    daysAgo: 12,
  },

  /* --- Other buyers ------------------------------------------------------- */
  {
    userId: buyerId('bloom'),
    type: NOTIFICATION_TYPE.DELIVERY_SUBMITTED,
    title: 'Zoe Okonkwo submitted a delivery',
    body: 'Swatch and texture photography for the tinted SPF range is ready to review. Auto-acceptance runs in one day.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_bloom_texture'),
    read: false,
    daysAgo: 4,
  },
  {
    userId: buyerId('bloom'),
    type: NOTIFICATION_TYPE.DISPUTE_RESOLVED,
    title: 'Your dispute was resolved',
    body: 'The full amount of $610 has been refunded to your payment method after no deliverables were submitted.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('cancelled_bloom_serum'),
    read: true,
    daysAgo: 33,
  },
  {
    userId: buyerId('atlas'),
    type: NOTIFICATION_TYPE.DELIVERY_SUBMITTED,
    title: 'Isla Bergstrom submitted a delivery',
    body: 'Property photography for the three Algarve partner hotels is ready to review.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_atlas_hotel'),
    read: false,
    daysAgo: 2,
  },
  {
    userId: buyerId('pulse'),
    type: NOTIFICATION_TYPE.PROPOSAL_RECEIVED,
    title: 'Four proposals on your walkthrough brief',
    body: 'Quotes range from $820 to $1,200 with turnarounds between 10 and 16 days.',
    entityType: ENTITY_TYPE.REQUEST,
    entityId: requestId('open_pulse_walkthrough'),
    read: false,
    daysAgo: 0.8,
  },
  {
    userId: buyerId('nimbus'),
    type: NOTIFICATION_TYPE.PROPOSAL_ACCEPTED,
    title: 'Your order is waiting for payment',
    body: 'You accepted Liam Chen’s proposal for the connected training app film. Fund the order to start the clock.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_nimbus_app'),
    read: false,
    daysAgo: 1,
  },
  {
    userId: buyerId('craftware'),
    type: NOTIFICATION_TYPE.DISPUTE_MESSAGE,
    title: 'BetterBlue replied to your dispute',
    body: 'A reviewer has asked when the plunge head is expected, so the fourth film can be completed rather than refunded.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_craftware_demo'),
    read: true,
    daysAgo: 16,
  },
  {
    userId: buyerId('urbannest'),
    type: NOTIFICATION_TYPE.DISPUTE_RESOLVED,
    title: 'Dispute closed',
    body: 'The delivered masters were confirmed sharp at full resolution, so the payment has been released to the creator.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('completed_urbannest_loft'),
    read: true,
    daysAgo: 14,
  },
  {
    userId: buyerId('cocoa'),
    type: NOTIFICATION_TYPE.ORDER_PAID,
    title: 'Payment held in escrow',
    body: '$940 is held for “15 lifestyle photos for a single-origin gift box launch” and releases when you accept the delivery.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_cocoa_gift'),
    read: true,
    daysAgo: 5.8,
  },

  /* --- Other creators ----------------------------------------------------- */
  {
    userId: creatorId('liam'),
    type: NOTIFICATION_TYPE.PROPOSAL_ACCEPTED,
    title: 'Nimbus Fitness accepted your proposal',
    body: 'The order opens once the buyer funds it. You will be notified the moment payment is held.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_nimbus_app'),
    read: true,
    daysAgo: 1,
  },
  {
    userId: creatorId('liam'),
    type: NOTIFICATION_TYPE.PAYOUT_PROCESSED,
    title: 'Payout is being processed',
    body: 'Your $1,500 payout has moved to processing and will be marked paid once the transfer settles.',
    entityType: ENTITY_TYPE.PAYOUT,
    entityId: payouts[2].id,
    read: false,
    daysAgo: 4,
  },
  {
    userId: creatorId('zoe'),
    type: NOTIFICATION_TYPE.PAYMENT_RELEASED,
    title: 'Payment released',
    body: '$816 has been added to your balance from the barrier repair campaign film.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('completed_bloom_campaign'),
    read: true,
    daysAgo: 31,
  },
  {
    userId: creatorId('zoe'),
    type: NOTIFICATION_TYPE.MODERATION_APPROVED,
    title: 'Portfolio item approved',
    body: 'Your studio campaign film for the sustainable denim drop was approved and is now live on your public profile.',
    entityType: ENTITY_TYPE.PORTFOLIO_ITEM,
    entityId: itemNamed('Studio campaign film for a sustainable denim drop'),
    read: false,
    daysAgo: 8,
  },
  {
    userId: creatorId('diego'),
    type: NOTIFICATION_TYPE.MODERATION_REVISION,
    title: 'Changes requested on your submission',
    body: 'The resistance band demonstration set needs changes before it can be published. The reviewer’s notes are on the item.',
    entityType: ENTITY_TYPE.PORTFOLIO_ITEM,
    entityId: itemNamed('Resistance band range demonstration set'),
    read: false,
    daysAgo: 17,
  },
  {
    userId: creatorId('yuki'),
    type: NOTIFICATION_TYPE.REVISION_REQUESTED,
    title: 'UrbanNest Interiors requested a revision',
    body: 'Six frames in the white finish need a re-grade to match the neutral reference. Everything else is approved.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('awarded_urbannest_shelf'),
    read: false,
    daysAgo: 7,
  },
  {
    userId: creatorId('sara'),
    type: NOTIFICATION_TYPE.DISPUTE_OPENED,
    title: 'A dispute was opened on your order',
    body: 'Pulse SaaS opened a late delivery dispute. Respond in the case thread with your current status and expected delivery date.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_pulse_explainer'),
    read: true,
    daysAgo: 6,
  },
  {
    userId: creatorId('noah'),
    type: NOTIFICATION_TYPE.DISPUTE_OPENED,
    title: 'A dispute was opened on your order',
    body: 'Craftware Tools raised a scope dispute about the missing fourth film. A reviewer has been assigned.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('awarded_craftware_demo'),
    read: true,
    daysAgo: 18,
  },
  {
    userId: creatorId('isla'),
    type: NOTIFICATION_TYPE.PAYMENT_RELEASED,
    title: 'Payment released',
    body: '$784 has been added to your balance from the Porto guesthouse property set.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('h12'),
    read: true,
    daysAgo: 54,
  },
  {
    userId: creatorId('mateo'),
    type: NOTIFICATION_TYPE.MODERATION_REVISION,
    title: 'Changes requested on your submission',
    body: 'The lakeside venue tour film needs changes before it can be published. Update it and send it back for review.',
    entityType: ENTITY_TYPE.PORTFOLIO_ITEM,
    entityId: itemNamed('Lakeside venue tour film'),
    read: false,
    daysAgo: 12,
  },
  {
    userId: creatorId('mateo'),
    type: NOTIFICATION_TYPE.DISPUTE_RESOLVED,
    title: 'Dispute resolved with a partial refund',
    body: 'A quarter of the order value was returned to Atlas Travel Co and $492 was released to your balance.',
    entityType: ENTITY_TYPE.DISPUTE,
    entityId: disputeOn('completed_atlas_villa'),
    read: true,
    daysAgo: 18,
  },
  {
    userId: creatorId('ethan'),
    type: NOTIFICATION_TYPE.MODERATION_REJECTED,
    title: 'Submission rejected',
    body: 'The new-build show home series is missing category, content type, and usage details. Add them and re-submit.',
    entityType: ENTITY_TYPE.PORTFOLIO_ITEM,
    entityId: itemNamed('New-build show home series'),
    read: false,
    daysAgo: 6,
  },
  {
    userId: creatorId('chloe'),
    type: NOTIFICATION_TYPE.ACCOUNT_STATUS_CHANGED,
    title: 'Your account has been suspended',
    body: 'Your account is suspended while our Trust & Safety team completes a licensing review. Payouts are on hold and your balance stays intact. Contact support if you have questions.',
    entityType: ENTITY_TYPE.USER,
    entityId: creatorId('chloe'),
    read: true,
    daysAgo: 29,
  },
  {
    userId: creatorId('amara'),
    type: NOTIFICATION_TYPE.ORDER_COMPLETED,
    title: 'Order completed',
    body: 'Cocoa & Co accepted the flagship cafe opening coverage and left a 4-star review.',
    entityType: ENTITY_TYPE.ORDER,
    entityId: order('h24'),
    read: true,
    daysAgo: 18,
  },
]

export const notifications = NOTIFICATION_SOURCE.map((source, index) =>
  // `entityType`/`entityId` are optional — a platform announcement links to
  // nothing in particular, so both keys are omitted rather than nulled.
  compact({
    id: seqId('ntf', index + 1),
    userId: source.userId,
    type: source.type,
    title: source.title,
    body: source.body,
    entityType: source.entityType,
    entityId: source.entityId,
    read: source.read,
    createdAt: daysAgo(source.daysAgo, 20, 15),
  })
)
